name = 'stremio-streaming-catalogs-addon'
main = "src/worker.js"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[vars]
# VITE_ADMIN_TOKEN = ""
# VITE_APP_URL = "https://your-worker.workers.dev"

[assets]
directory = "./vue/dist"
binding = "ASSETS"
